import { describe, expect, it, vi } from 'vitest';
import type { BibleContentResponse } from '@youversion/platform-react-native-expo-core';
import { ApiClient, BibleClient } from '@youversion/platform-core';
vi.mock('react-native', () => ({}));
vi.mock('react-native-mmkv', () => ({ createMMKV: () => ({ getString: () => undefined, set: () => {}, remove: () => {}, getAllKeys: () => [] }) }));
import { createBibleContentClient } from '../../node_modules/@youversion/platform-react-native-expo-core/build/bible-content/client';
import {
  buildBibleContentPath,
  createBibleContentPreloader,
} from '../../src/services/bibleContentPreload';

describe('BibleContentPreloader', () => {
  it('matches the actual BibleReader.Content request options generated by BibleClient', async () => {
    const webFetch = vi.fn(async (_url: string) => new Response(JSON.stringify({ id: '1TI.1', content: '<p>fixture</p>', reference: 'Fixture book 1' }), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    }));
    vi.stubGlobal('fetch', webFetch);
    const bibleClient = new BibleClient(new ApiClient({ appKey: 'test-app', apiHost: 'api.reader' }));
    await bibleClient.getPassage(46, '1TI.1', 'html', true, true, false);
    const requestUrl = new URL(String(webFetch.mock.calls[0][0]));
    const actualReaderPath = `${requestUrl.pathname}${requestUrl.search}`;
    expect(buildBibleContentPath(46, '1TI.1')).toBe(actualReaderPath);
    vi.unstubAllGlobals();
  });

  it('builds the same chapter request shape as usePassage', () => {
    expect(buildBibleContentPath(46, '1TI.1')).toBe(
      '/v1/bibles/46/passages/1TI.1?format=html&include_headings=true&include_notes=true',
    );
  });

  it('prioritizes the active chapter, limits background work to two, and coalesces duplicate inflight paths', async () => {
    const pending = new Map<string, { resolve: (value: BibleContentResponse) => void }>();
    const fetchContent = vi.fn((request: { path: string }) => new Promise<BibleContentResponse>((resolve) => {
      pending.set(request.path, { resolve });
    }));
    const preloader = createBibleContentPreloader(fetchContent);

    const first = preloader.enqueue({ versionId: 46, references: ['1TI.1', '1TI.2', '1TI.3'], activeReferenceIndex: 1 });
    const duplicate = preloader.enqueue({ versionId: 46, references: ['1TI.1', '1TI.2'], activeReferenceIndex: 1 });
    expect(fetchContent).toHaveBeenCalledTimes(2);
    expect(fetchContent.mock.calls.map(([request]) => request.path)).toEqual([
      buildBibleContentPath(46, '1TI.2'),
      buildBibleContentPath(46, '1TI.1'),
    ]);

    pending.get(buildBibleContentPath(46, '1TI.2'))!.resolve({ status: 200, body: '{}', contentType: 'application/json' });
    await Promise.resolve(); await Promise.resolve(); await Promise.resolve();
    expect(fetchContent).toHaveBeenCalledTimes(3);
    expect(fetchContent.mock.calls[2][0].path).toBe(buildBibleContentPath(46, '1TI.3'));

    for (const item of pending.values()) item.resolve({ status: 200, body: '{}', contentType: 'application/json' });
    await Promise.all([first, duplicate]);
  });

  it('cancels an old generation so late results do not start queued chapters', async () => {
    let resolveFirst!: (value: BibleContentResponse) => void;
    const fetchContent = vi.fn((request: { path: string }) => new Promise<BibleContentResponse>((resolve) => {
      if (request.path.endsWith('1TI.1?format=html&include_headings=true&include_notes=true')) resolveFirst = resolve;
    }));
    const preloader = createBibleContentPreloader(fetchContent);
    const run = preloader.enqueue({ versionId: 46, references: ['1TI.1', '1TI.2', '1TI.3'] });
    preloader.cancel();
    expect(resolveFirst).toBeTypeOf('function');
    resolveFirst({ status: 200, body: '{}', contentType: 'application/json' });
    await run;
    expect(fetchContent).toHaveBeenCalledTimes(2);
  });

  it('swallows preload failures so reading can retry on demand', async () => {
    const fetchContent = vi.fn(async () => { throw new Error('transport detail'); });
    await expect(createBibleContentPreloader(fetchContent).enqueue({ versionId: 46, references: ['1TI.1'] })).resolves.toEqual({
      attempted: 1,
      completed: 0,
      failed: 1,
    });
  });

  it('coalesces the same native content request across separate SDK client instances', async () => {
    const path = buildBibleContentPath(46, '1TI.1');
    let release!: (response: Response) => void;
    const fetcher = vi.fn(() => new Promise<Response>((resolve) => { release = resolve; }));
    const store = {
      read: () => null,
      write: vi.fn(),
      listVersionIds: () => [],
      sweep: vi.fn(),
    };
    const options = { appKey: 'test-app', apiHost: 'api.test', installationId: 'installation-1', fetch: fetcher, store, timeoutMs: 1_000 };
    const first = createBibleContentClient(options);
    const second = createBibleContentClient(options);
    const one = first({ path });
    const two = second({ path });
    expect(fetcher).toHaveBeenCalledTimes(1);
    release(new Response('{}', { status: 200, headers: { 'cache-control': 'public, max-age=1800', 'content-type': 'application/json' } }));
    await expect(Promise.all([one, two])).resolves.toHaveLength(2);
  });

  it('keeps SDK TTL and error semantics after inflight coalescing', async () => {
    const path = buildBibleContentPath(46, '1TI.2');
    let now = 0;
    const entries = new Map<string, { body: string; expiresAt: number }>();
    const store = {
      read: (_versionId: number, key: string, at: number) => {
        const entry = entries.get(key);
        return entry && entry.expiresAt > at ? entry : null;
      },
      write: vi.fn((_versionId: number, key: string, entry: { body: string; expiresAt: number }) => entries.set(key, entry)),
      listVersionIds: () => [],
      sweep: vi.fn(),
    };
    const fetcher = vi.fn(async () => new Response('{"ok":true}', { status: 200, headers: { 'cache-control': 'public, max-age=1800', 'content-type': 'application/json' } }));
    const client = createBibleContentClient({ appKey: 'test-app', apiHost: 'api.ttl', installationId: 'installation-ttl', fetch: fetcher, store, now: () => now });
    await client({ path });
    await client({ path });
    expect(fetcher).toHaveBeenCalledTimes(1);
    now = 1_800_001;
    await client({ path });
    expect(fetcher).toHaveBeenCalledTimes(2);

    const errorFetcher = vi.fn(async () => new Response('failure', { status: 503, headers: { 'cache-control': 'no-store' } }));
    const errorClient = createBibleContentClient({ appKey: 'test-app', apiHost: 'api.error', installationId: 'installation-error', fetch: errorFetcher, store, now: () => now });
    const writesBeforeError = store.write.mock.calls.length;
    await clientResponse(errorClient, path);
    await clientResponse(errorClient, path);
    expect(errorFetcher).toHaveBeenCalledTimes(2);
    expect(store.write).toHaveBeenCalledTimes(writesBeforeError);
  });
});

async function clientResponse(client: ReturnType<typeof createBibleContentClient>, path: string): Promise<void> {
  await client({ path });
}
