import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { verifyCandidate } from '../scripts/verify-candidate';

describe('candidate boundary', () => {
  // android/ is generated by `expo prebuild` and not tracked; only the build worktree has it, and there this runs.
  it.skipIf(!existsSync(join(process.cwd(), 'android', 'gradle.properties')))('accepts the fixture-marked Android package without secrets', async () => {
    const receipt = await verifyCandidate(process.cwd());
    expect(receipt.androidPackage).toBe('org.qingmu.youth');
    expect(receipt.fixture).toBe(true);
    expect(receipt.contentMode).toBe('C_PENDING_ACCESS');
    expect(receipt.forbiddenMatches).toEqual([]);
  });
});
