import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { theme } from '../Theme';

export interface ActionSheetAction { label: string; onPress: () => void; destructive?: boolean; disabled?: boolean; }
export function ActionSheet({ visible, title, actions, onClose, children }: { visible: boolean; title: string; actions?: ActionSheetAction[]; onClose: () => void; children?: React.ReactNode }) {
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose} accessibilityViewIsModal>
    <View style={styles.scrim}><View style={styles.sheet}><View style={styles.heading}><Text style={styles.title}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="關閉操作" onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>{children}{actions?.map((action) => <Pressable key={action.label} accessibilityRole="button" accessibilityLabel={action.label} disabled={action.disabled} onPress={action.onPress} style={[styles.action, action.destructive && styles.destructive, action.disabled && styles.disabled]}><Text style={[styles.actionText, action.destructive && styles.destructiveText]}>{action.label}</Text></Pressable>)}</View></View>
  </Modal>;
}
const styles = StyleSheet.create({ scrim: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(21,48,42,0.28)' }, sheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: theme.radius.card, borderTopRightRadius: theme.radius.card, padding: theme.spacing.lg, gap: theme.spacing.sm }, heading: { minHeight: theme.control.tap, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: theme.colors.ink, fontSize: theme.type.heading.size, fontWeight: '800' }, close: { minWidth: theme.control.tap, minHeight: theme.control.tap, alignItems: 'center', justifyContent: 'center' }, closeText: { color: theme.colors.ink, fontSize: 28 }, action: { minHeight: theme.control.tap, alignItems: 'center', justifyContent: 'center', borderRadius: theme.radius.button, backgroundColor: theme.colors.primary }, actionText: { color: theme.colors.white, fontSize: theme.type.body.size, fontWeight: '800' }, destructive: { backgroundColor: theme.colors.accentSoft }, destructiveText: { color: theme.colors.accent }, disabled: { opacity: 0.45 } });
