import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { Redemption } from '../../services/gamificationApiClient';
import { theme } from '../Theme';

export function RedemptionList({ redemptions, canReverse, onReverse }: { redemptions: Redemption[]; canReverse?: boolean; onReverse?: (redemptionId: string, reason: string) => void }) {
  const [selected, setSelected] = useState<string | null>(null); const [reason, setReason] = useState('');
  return <View style={styles.list}>{redemptions.length === 0 ? <Text style={styles.empty}>目前沒有領取紀錄。</Text> : redemptions.map((item) => <View key={item.redemptionId} style={styles.row}><View style={styles.copy}><Text style={styles.name}>{item.rewardName}</Text><Text style={styles.detail}>{item.costPoints} 分 · {item.status === 'REVERSED' ? '已撤銷' : '已完成'}</Text></View>{canReverse && item.status === 'COMPLETED' && onReverse ? <Pressable accessibilityRole="button" accessibilityLabel={`撤銷${item.rewardName}`} onPress={() => { setSelected(item.redemptionId); setReason(''); }} style={styles.reverse}><Text style={styles.reverseText}>撤銷</Text></Pressable> : null}{selected === item.redemptionId ? <View style={styles.confirm}><TextInput accessibilityLabel="撤銷理由" value={reason} onChangeText={setReason} placeholder="撤銷理由" style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="確認撤銷兌換" disabled={!reason.trim()} onPress={() => { onReverse?.(item.redemptionId, reason.trim()); setSelected(null); setReason(''); }} style={[styles.confirmButton, !reason.trim() && styles.disabled]}><Text style={styles.confirmText}>確認撤銷</Text></Pressable></View> : null}</View>)}</View>;
}

const styles = StyleSheet.create({ list: { gap: theme.spacing.xs }, row: { minHeight: theme.control.tap, padding: theme.spacing.sm, backgroundColor: theme.colors.surface, borderColor: theme.colors.border, borderWidth: theme.control.hairline, borderRadius: theme.radius.card, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: theme.spacing.sm }, copy: { flex: 1, gap: theme.spacing.xxs }, name: { color: theme.colors.ink, fontSize: theme.type.body.size, fontWeight: '700' }, detail: { color: theme.colors.muted, fontSize: theme.type.caption.size }, reverse: { minWidth: theme.control.tap, minHeight: theme.control.tap, alignItems: 'center', justifyContent: 'center' }, reverseText: { color: theme.colors.accent, fontSize: theme.type.caption.size, fontWeight: '800' }, confirm: { width: '100%', gap: theme.spacing.xs }, input: { minHeight: theme.control.tap, borderColor: theme.colors.borderStrong, borderWidth: theme.control.hairline, borderRadius: theme.radius.button, paddingHorizontal: theme.spacing.sm, color: theme.colors.ink }, confirmButton: { minHeight: theme.control.tap, borderRadius: theme.radius.button, backgroundColor: theme.colors.accent, alignItems: 'center', justifyContent: 'center' }, confirmText: { color: theme.colors.white, fontWeight: '800' }, disabled: { opacity: 0.45 }, empty: { color: theme.colors.muted, fontSize: theme.type.body.size, paddingVertical: theme.spacing.md } });
