import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { Reward } from '../../services/gamificationApiClient';
import { theme } from '../Theme';

export function RewardControls({ rewards, selectedRewardId, canEdit, onSelect, admin, onCreate, onArchive, onUpdate, onRedeem, redeemableBalance }: { rewards: Reward[]; selectedRewardId?: string | null; canEdit: boolean; onSelect?: (rewardId: string) => void; admin?: boolean; onCreate?: (name: string, costPoints: number) => void; onArchive?: (rewardId: string) => void; onUpdate?: (rewardId: string, patch: { name?: string; costPoints?: number }) => void; onRedeem?: (rewardId: string) => void; redeemableBalance?: number }) {
  const [expanded, setExpanded] = useState(false); const [name, setName] = useState(''); const [cost, setCost] = useState(''); const [candidate, setCandidate] = useState<string | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [editName, setEditName] = useState(''); const [editCost, setEditCost] = useState('');
  const active = rewards.filter((reward) => reward.active && (onRedeem ? redeemableBalance === undefined || reward.costPoints <= redeemableBalance : true));
  const visible = admin || expanded || Boolean(onRedeem) ? active : [];
  return <View style={styles.container}><Text style={styles.label}>{admin ? '獎品目錄' : '選擇目標獎品'}</Text>{visible.length === 0 && !admin ? <Text style={styles.empty}>尚未設定獎品</Text> : null}{visible.map((reward) => <View key={reward.rewardId} style={styles.row}><Pressable accessibilityRole={onRedeem ? 'button' : 'radio'} accessibilityState={{ selected: selectedRewardId === reward.rewardId || candidate === reward.rewardId }} disabled={!canEdit && !onRedeem} onPress={() => onRedeem ? setCandidate(reward.rewardId) : onSelect?.(reward.rewardId)} style={styles.choice}><Text style={styles.name}>{reward.name}</Text><Text style={styles.cost}>{reward.costPoints} 分</Text></Pressable>{admin ? <><Pressable accessibilityRole="button" accessibilityLabel={`編輯${reward.name}`} onPress={() => { setEditingId(reward.rewardId); setEditName(reward.name); setEditCost(String(reward.costPoints)); }} style={styles.archive}><Text style={styles.archiveText}>編輯</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`下架${reward.name}`} onPress={() => onArchive?.(reward.rewardId)} style={styles.archive}><Text style={styles.archiveText}>下架</Text></Pressable>{editingId === reward.rewardId ? <View style={styles.edit}><TextInput accessibilityLabel="編輯獎品名稱" value={editName} onChangeText={setEditName} style={styles.input} /><TextInput accessibilityLabel="編輯獎品分數" value={editCost} onChangeText={setEditCost} keyboardType="number-pad" style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="儲存獎品修改" onPress={() => { const amount = Number(editCost); if (editName.trim() && Number.isInteger(amount) && amount > 0) { onUpdate?.(reward.rewardId, { name: editName.trim(), costPoints: amount }); setEditingId(null); } }} style={styles.button}><Text style={styles.buttonText}>儲存修改</Text></Pressable></View> : null}</> : null}</View>)}{onRedeem && candidate ? <Pressable accessibilityRole="button" accessibilityLabel="確認交付兌換" onPress={() => { onRedeem(candidate); setCandidate(null); }} style={styles.button}><Text style={styles.buttonText}>確認交付</Text></Pressable> : null}{canEdit && !admin ? <Pressable accessibilityRole="button" accessibilityLabel="顯示獎品選擇" onPress={() => setExpanded(!expanded)} style={styles.toggle}><Text style={styles.toggleText}>{expanded ? '收起' : '選擇獎品'}</Text></Pressable> : null}{admin ? <><TextInput accessibilityLabel="獎品名稱" value={name} onChangeText={setName} placeholder="獎品名稱" style={styles.input} /><TextInput accessibilityLabel="獎品分數" value={cost} onChangeText={setCost} keyboardType="number-pad" placeholder="所需積分" style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="建立獎品" onPress={() => { const amount = Number(cost); if (name.trim() && Number.isInteger(amount) && amount > 0) { onCreate?.(name.trim(), amount); setName(''); setCost(''); } }} style={styles.button}><Text style={styles.buttonText}>建立獎品</Text></Pressable></> : null}</View>;
}
const styles = StyleSheet.create({ container: { gap: theme.spacing.xs }, label: { color: theme.colors.muted, fontSize: theme.type.caption.size }, empty: { color: theme.colors.muted, fontSize: theme.type.label.size }, row: { minHeight: theme.control.tap, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: theme.spacing.sm, paddingHorizontal: theme.spacing.sm, borderBottomWidth: theme.control.hairline, borderBottomColor: theme.colors.border }, choice: { flex: 1, minHeight: theme.control.tap, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm }, name: { flex: 1, color: theme.colors.ink, fontSize: theme.type.body.size }, cost: { color: theme.colors.primary, fontSize: theme.type.label.size, fontWeight: '800' }, archive: { minHeight: theme.control.tap, minWidth: theme.control.tap, alignItems: 'center', justifyContent: 'center' }, archiveText: { color: theme.colors.accent, fontSize: theme.type.caption.size }, edit: { width: '100%', gap: theme.spacing.xs }, toggle: { minHeight: theme.control.tap, alignItems: 'center', justifyContent: 'center', borderRadius: theme.radius.button, borderColor: theme.colors.primary, borderWidth: theme.control.hairline }, toggleText: { color: theme.colors.primary, fontWeight: '800' }, input: { minHeight: theme.control.tap, borderRadius: theme.radius.button, borderColor: theme.colors.borderStrong, borderWidth: theme.control.hairline, paddingHorizontal: theme.spacing.md, color: theme.colors.ink }, button: { minHeight: theme.control.tap, borderRadius: theme.radius.button, backgroundColor: theme.colors.primary, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: theme.colors.white, fontWeight: '800' } });
